# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymmy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplanexercisedetail',
            name='breaks_between_exercises',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingplanexerciseprogress',
            name='breaks_between_sets',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
